---
# Actions that take place on the main branch,
# driven by external dm-api events.

# -----------------
# Control variables (GitHub Secrets)
# -----------------
#
# (n/a)
#
# -----------
# Environment (GitHub Environments)
# -----------
#
# Environment         (n/a)

name: publish

on:
  repository_dispatch:
    types: account-server-api

env:
  NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
  CI_PIPELINE_ID: ${{ github.event.client_payload.CI_PIPELINE_ID }}
  CI_COMMIT_TAG: ${{ github.event.client_payload.CI_COMMIT_TAG }}
  GITLAB_API: https://gitlab.com/api/v4/projects
  GITLAB_API_TOKEN: ${{ secrets.ACCOUNT_SERVER_TOKEN }}
  GITLAB_PROJECT: 30392726
  OPENAPI_FILE: openapi.yaml
  OPENAPI_PATH: app%2Fopenapi

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        uses: InformaticsMatters/openapi-js-client-generator/build-client@main
        with:
          API_NAME: account-server-api
          GITLAB_API: ${GITLAB_API}
          GITLAB_API_TOKEN: ${GITLAB_API_TOKEN}
          GITLAB_PROJECT: ${GITLAB_PROJECT}
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: publish
        uses: InformaticsMatters/openapi-js-client-generator/publish-client@main
        with:
          CI_COMMIT_TAG: ${CI_COMMIT_TAG}
